### ISSUE TITLE
Lava-heated anvil repair speed is slower than it should be

### ISSUE THREAD

**Issue by hlqkj** [BluebirdGreycoat/musttest_game#13]
In my understanding, lava should give the best repair speed, while fire a slower but still acceptable one.

However, I noticed that, when both are present, the fire speed prevails (as it should be, according to code below). This doesn't make much sense, as it would imply that a fire is somehow "shielding" out the heat from the lava?

https://github.com/BluebirdGreycoat/musttest_game/blob/14811a338fd6b576a8386103c202a3bca7c685c0/mods/anvil/init.lua#L815-L821

**Comment by BluebirdGreycoat** [comment]
9d08e6ebf37a6727060774b6641965cf3f89148e
