### ISSUE TITLE
Ghost bones

### ISSUE THREAD

**Issue by hlqkj** [BluebirdGreycoat/musttest_game#14]
This:

https://github.com/BluebirdGreycoat/musttest_game/blob/7193f71a596f0d26b0068ac1ec5376b839315450/mods/protector/tool.lua#L336-L340

and thus I assume also this:

https://github.com/BluebirdGreycoat/musttest_game/blob/7193f71a596f0d26b0068ac1ec5376b839315450/mods/protector/tool.lua#L136-L140

seems to fail when trying to push a protector in a position that *was* once occupied by bones, but has since been freed and subsequently occupied by something else (specifically, the case involved a brimstone source node).

I did some tests and it seems that even after a node gets replaced `minetest.get_inventory()` still ~~dumbly~~(Edit: I'm not sure if this is actually dumb, or not...) returns an `InvRef` that seems to be empty (`:get_lists()` returns an empty table).

I am not sure if all this is supposed to happen or not. For sure returning `nil` is undocumented behaviour according to [API docs](https://github.com/minetest/minetest/blob/master/doc/lua_api.md?plain=1#L6541). Posted a question on the Minetest repo (issue no. 15243 - not pasting the link to avoid cross-linking, as usual).

**Comment by BluebirdGreycoat** [comment]
> specifically, the case involved a brimstone source node

Speculation: since it's a liquid, the engine might not be cleaning up the metadata when the liquid renews/updates.

**Comment by hlqkj** [comment]
Yes, that's what I thought. Testing confirms that using `set_node()` explicitly clears the metadata, and subsequently `get_inventory()` works as "expected". I don't know how the liquid physics sets a node internally.

**Comment by hlqkj** [comment]
Having just closed the issue on the (ex, sigh) Minetest repository, I don't think that waiting here for it to be figured out there has any sense anymore. Also, the game works as it is for just everyone, but the very single player who encountered this particular situation, so not worth wasting time on it. Closing.

**Comment by BluebirdGreycoat** [comment]
Note to self: the info in Minetest repo issue 15243 hints to me the right way to fix this: have the game keep track of all possible inventory-managing nodes, and simply check the nodename against the list.

**Comment by BluebirdGreycoat** [comment]
This should fix it (some adjacent commits, too): 3e6ffb3974c5122a4c0e1b4475095a3c2f25b10a
