### ISSUE TITLE
Paintings get lost if placement fails

### ISSUE THREAD

**Issue by hlqkj** [BluebirdGreycoat/musttest_game#7]
When trying to place a `xdecor:painting_1` item, if the placement fails for some reason (my case was lack of space in the pointed thing’s above) an item is unconditionally taken from the stack, thus getting lost.

Line of interest:
https://github.com/BluebirdGreycoat/musttest_game/blob/eeb0d43046390b4a2765e6c1059e27471bd6fe71/mods/xdecor/src/nodes.lua#L624

**Comment by BluebirdGreycoat** [comment]
should be fixed by a74053bac5c5c222a9f0dcdd9d2c7bb9dec96768

**Comment by hlqkj** [comment]
Thank you! 😊
