### ISSUE TITLE
The "Abyss return Midfeld" flag is not cleared when using the stone world scepter

### ISSUE THREAD

**Issue by hlqkj** [BluebirdGreycoat/musttest_game#8]
If a player dies in Midfeld, and a scepter is used on them, their `abyss_return_midfeld` flag doesn't get cleared. As a result, a subsequent death (in any realm) sends the player to the Outback again instead of using their bed respawn position.

**Comment by BluebirdGreycoat** [comment]
Thanks for the report! Will fix when I get some time.

**Comment by BluebirdGreycoat** [comment]
Fixed!
